language: node_js
node_js:
- 4.1
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: SGJJtLlUz3J7mb6yxZwpRTQp6n/35uJLJB+oM0kt9WoQVfaHFvienA5HsyaHy92Ln8Gg8YnHsW7zD7QC86JppiqNb4KJ5aKkr2ARCHu0beH82IsArlstOmjfJ7fhbpvTqGVOrU0jgUMwrFS5GPZmOIyVyb9nWxNfNIqRxjaRalI=
  on:
    tags: true
    all_branches: true
