language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: MWRClo7/hxMeTQwk3W6QtS4iCp/EDuIDtgqdS/PaHG9a9MdwaRtGbxdGkuw4e47LujJMqDfl5RpDykXPSRPpXK27yggXr+NsFIzVsXxm8RxwCyHa7C4Yz8V+Q4fEBDhUWRvwKvQs/mQO+UUCs9ilw/lmJHoqawzaB6VYoOxHCG0=
  on:
    tags: true
    all_branches: true
